### ISSUE TITLE
Site favicon

### ISSUE THREAD

**Issue by gsf** [sheltr/sheltr#2]
Anyone feeling favicon-inspired? I hate seeing lots of favicon.ico 404s in our web logs.

**Comment by caseycesari** [comment]
I create favicon.ico and placed it in the /static/img dir. It's a simplified version of the house from the sheltr.org banner.

**Comment by gsf** [comment]
Nice! In 1a795a60bfb6735f5f30802250745b6edb9257d9 I moved it to the root of static so it should just show up.
